language: node_js
node_js:
  - "12.18.2"
install: npm install
script:
  #- xvfb-maybe node_modules/.bin/karma start test/unit/karma.conf.js
  #- yarn run pack && xvfb-maybe node_modules/.bin/mocha test/e2e
  - npm run release
# - yarn run build:docs
before_script:
  - git pull origin dva-dem
branches:
  only:
    - master
# 指定缓存模块，可选。缓存可加快编译速度。
cache:
  directories:
    - node_modules
# after_script:
#   - cd ./public
#   - git init
#   - git config user.name "jackobj"
#   - git config user.email "260163518@11.com"
#   - git add .
#   - git commit -m "update"
#   - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
#- git push --force --quiet "https://${GH_TOKEN}@${你得项目地址(如果源码跟发布的不在一个分支 这里是分发布用的分支地址)，不带https}" master:master
#默认一个分支可以忽略此配置--监视github仓库中的master分支，分支出现变化就执行build
#branches:
#  only:
#    - blogTS
